config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "spendings#index"

  resources :spendings, only: [:index, :new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spending.rb
class Spending < ApplicationRecord
  belongs_to :user

  validates :useday, presence: true
  validates :place,  presence: true
  validates :money,  presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :nickname, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :spendings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/spendings_controller.rb
class SpendingsController < ApplicationController

  def index
    @spendings = Spending.all
  end

  def new
    @spending = Spending.new
  end

  def create
    @spending = Spending.new(spending_params)
    if @spending.save
      redirect_to root_path
    else
      render :new
    end
  end


  private

  def spending_params
    params.require(:spending).permit(:useday, :place, :detail, :money).merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spendings_helper.rb
module SpendingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Spending App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="logo__area">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
            </div>
            
            <% if user_signed_in? %>

            <div class="nav__left">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
                <%= link_to "記録する", new_spending_path, class: :nav__btn %>
            </div>
              <% else %>
                <div class="nav__right">
                  <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
                  <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
                </div>
             <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © SPENDING APP All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/spendings/_form.html.erb
<%= form_with model: spending, local: true do |f|%>


  <div class="field">
    <%= f.label :place, "日付" %>          <span class="indispensable">*</span><br />
    </div>

    <div class='day__field'>
      <%= raw sprintf(
                  f.date_select(
                    :useday,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 2022,
                    end_year: (Time.now.year - 2),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>


        <div class="field">
            <%= f.label :place, "場所" %>
              <span class="indispensable">*</span><br />
          <%= f.text_field :place, class:"text" %>
        </div>

  <div class="field">
    <%= f.label :detail, "内容" %><br />
          <input class="text" type="text" name="内容">
  </div>

        <div class="field">
            <%= f.label :detail, "金額" %>
              <span class="indispensable">*</span><br />
          <%= f.text_field :money, class:"text" %>
        </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/spendings/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        こんにちは、
        <%= "#{current_user.nickname}さん" %>
      </div>
    <% end %>
          <div class="card__wrapper"></div>
  </div>
</main>

app/views/spendings/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">支出記録</h2>
        <%= render partial: "form", locals: { spending: @spending } %>
    </div>
  </div>
</div>